# Generated by Django 5.2.16 on 2026-07-17 11:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("prefix", models.CharField(max_length=16, unique=True)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "scope",
                    models.CharField(
                        default="messages:read:approved", editable=False, max_length=40
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("actor", models.CharField(max_length=120)),
                ("action", models.CharField(max_length=120)),
                ("object_type", models.CharField(blank=True, max_length=80)),
                ("object_id", models.CharField(blank=True, max_length=80)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Mailbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("host", models.CharField(max_length=253)),
                ("port", models.PositiveIntegerField(default=993)),
                ("username", models.CharField(max_length=320)),
                ("password_encrypted", models.BinaryField()),
                (
                    "trusted_authserv_ids",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "Comma-separated Authentication-Results authserv-ids "
                            "controlled by the provider."
                        ),
                        max_length=500,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("uid_validity", models.PositiveBigIntegerField(blank=True, null=True)),
                ("last_uid", models.PositiveBigIntegerField(default=0)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("uid_validity", models.PositiveBigIntegerField()),
                ("uid", models.PositiveBigIntegerField()),
                ("message_id_hash", models.CharField(blank=True, max_length=64)),
                ("sender", models.CharField(blank=True, max_length=320)),
                ("sender_name", models.CharField(blank=True, max_length=320)),
                ("recipients", models.JSONField(default=list)),
                ("subject", models.CharField(blank=True, max_length=998)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("sanitized_text", models.TextField(blank=True)),
                ("links", models.JSONField(default=list)),
                ("authentication", models.JSONField(default=dict)),
                ("signals", models.JSONField(default=list)),
                (
                    "risk",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("category", models.CharField(default="uncategorized", max_length=80)),
                ("priority", models.PositiveSmallIntegerField(default=3)),
                ("summary", models.TextField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("quarantined", "Quarantined"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="quarantined",
                        max_length=20,
                    ),
                ),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mailbox",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="gateway.mailbox",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=255)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("sha256", models.CharField(max_length=64)),
                ("dangerous", models.BooleanField(default=False)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="gateway.message",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["state", "-received_at"], name="gateway_mes_state_8d55ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["category", "state"], name="gateway_mes_categor_389032_idx"),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                fields=("mailbox", "uid_validity", "uid"), name="unique_imap_message"
            ),
        ),
    ]
