# Generated by Django 5.2.16 on 2026-07-17 12:07

from django.db import migrations, models


def create_worker_quarantine_guard(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION mailgate_force_worker_quarantine()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF current_user = 'mailgate_worker' THEN
                NEW.state := 'quarantined';
                NEW.risk := CASE WHEN NEW.risk = 'high' THEN 'high' ELSE 'medium' END;
            END IF;
            RETURN NEW;
        END;
        $$;
        CREATE TRIGGER mailgate_worker_quarantine
        BEFORE INSERT ON gateway_message
        FOR EACH ROW EXECUTE FUNCTION mailgate_force_worker_quarantine();
        """
    )


def drop_worker_quarantine_guard(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        DROP TRIGGER IF EXISTS mailgate_worker_quarantine ON gateway_message;
        DROP FUNCTION IF EXISTS mailgate_force_worker_quarantine();
        """
    )


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["actor", "action", "-created_at"], name="gateway_aud_actor_ffeb22_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ("quarantined", "approved", "rejected"))),
                name="valid_message_state",
            ),
        ),
        migrations.RunPython(
            create_worker_quarantine_guard,
            drop_worker_quarantine_guard,
        ),
    ]
