# Generated by Django 5.2.16 on 2026-07-17 16:18
# SPDX-License-Identifier: AGPL-3.0-only

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0002_auditevent_gateway_aud_actor_ffeb22_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitoken",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
